#cloud-config

apt:
  primary:
    - arches: [default]
      uri: http://mirrors.aliyun.com/ubuntu/

groups:
  - docker

runcmd:
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https gnupg ca-certificates curl
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg
  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - sudo apt update
  - sudo apt install -y docker-ce docker-ce-cli containerd.io
  - sudo groupadd docker
  - sudo usermod -aG docker $USER
  - newgrp docker 
  - sudo apt install -y kubelet kubeadm kubectl
  - sudo swapoff -a

packages:
  net-tools